### ISSUE TITLE
Tag missing for 0.1.0 release

### ISSUE THREAD

**Issue by paolobarbolini** [jhpratt/num-conv#1]
Hi! While scraping releases from crates.io I've found this repository to be missing the tag for the v0.1.0 release. Could that be added please? The exact commit id can be found from https://docs.rs/crate/num-conv/0.1.0/source/.cargo_vcs_info.json

**Comment by jhpratt** [comment]
Admittedly finding the commit wouldn't be hard, as there's only a single commit in the repository :sweat_smile: I've tagged it, though. Thanks!
