### ISSUE TITLE
Saturating to smaller int sizes

### ISSUE THREAD

**Issue by tetrogem** [jhpratt/num-conv#2]
I don't know if this is in scope for this package, but this seems to be a useful alternative case for converting integers to smaller sizes; Where, instead of the least significant bits being what carries over, the larger int will be converted to the max of the smaller int if it is larger than what values it can hold. Example syntax below:
```rust
assert_eq!(10_u128.saturate::<u8>(), 10_u8);
assert_eq!(1000_u16.saturate::<u8>(), u8::MAX);
assert_eq!(u128::MAX.saturate::<u16>(), u16::MAX);
```
And for signed ints:
```rust
assert_eq!(-1000_i128.saturate::<i8>(), i8::MIN);
assert_eq!(-1000_i128.saturate::<u8>(), u8::MIN); // converts to 0
```

**Comment by jhpratt** [comment]
The purpose of this crate is to avoid `as` casts wherever possible. Saturating casts are not possible using `as`, so I do not intend to include that in this crate.
